WIP

diff --git a/cloudbuild.yml b/cloudbuild.yml
--- a/cloudbuild.yml
+++ b/cloudbuild.yml
@@ -136,8 +136,18 @@ steps:
         argocd app wait hipstershop-staging --health --timeout 300
 
         # TODO: implement proper e2e testing
+        tries=0
+        until (kubectl get services -n hipstershop frontend-external 2>&1 1>/dev/null); do
+          if [[ $$tries -gt 20 ]]; then
+            echo "Can't find frontend-external service. Aborting"
+            exit 1
+          fi
+          tries=$((tries+1))
+          sleep 2
+        done
         ip="$(kubectl get services -n hipstershop frontend-external \
             -o custom-columns=IP:.status.loadBalancer.ingress[0].ip --no-headers)"
+
         tries=0
         until (curl -sSL "http://$$ip" | grep '>Buy<' 1>/dev/null); do
           if [[ $$tries -gt 40 ]]; then
